import type { AccountMetrics, MarginPreview, ReconciliationStatus } from '../types'
import { pct, signedUsd, tone, usd } from '../format'
import { Panel, Metric } from './Panel'

export function RiskPanel({ account, preview, reconciliation, onControl }: { account: AccountMetrics; preview: MarginPreview; reconciliation: ReconciliationStatus; onControl: (action: string) => void }) {
  const qualifiedProjection = preview.qualified_for_next_batch
  const projectedCushion = qualifiedProjection && Number(account.net_liquidation) > 0 && preview.projected_excess_liquidity !== null
    ? Number(preview.projected_excess_liquidity) / Number(account.net_liquidation)
    : null
  return <Panel title="Margin & P&L" eyebrow="IBKR ACCOUNT / STRATEGY MARGIN">
    <div className="metric-grid"><Metric label="IBKR net liquidation" value={usd(account.net_liquidation)} /><Metric label="IBKR cash value" value={usd(account.total_cash_value)} /><Metric label="IBKR initial margin" value={usd(account.init_margin)} /><Metric label="IBKR maintenance margin" value={usd(account.maintenance_margin)} /><Metric label="IBKR full excess liquidity" value={usd(account.full_excess_liquidity)} /><Metric label="IBKR margin cushion" value={pct(account.cushion)} tone={Number(account.cushion) >= .5 ? 'positive' : 'negative'} /><Metric label="BUY 10 margin qualification" value={preview.qualification_status.replaceAll('_', ' ')} note={preview.qualification_detail} tone={qualifiedProjection ? 'positive' : 'negative'} /><Metric label="Next-batch initial margin" value={usd(qualifiedProjection ? preview.next_batch_initial_margin : null)} note={qualifiedProjection && preview.received_at ? `Current preview received ${new Date(preview.received_at).toLocaleTimeString()}` : 'Automatic refresh required before authorization'} /><Metric label="What-if maintenance change" value={usd(qualifiedProjection ? preview.maintenance_margin_change : null)} /><Metric label="Projected excess liquidity" value={usd(qualifiedProjection ? preview.projected_excess_liquidity : null)} /><Metric label="Projected margin cushion" value={pct(projectedCushion)} tone={projectedCushion !== null && projectedCushion >= .5 ? 'positive' : 'negative'} /><Metric label="Estimated commission" value={usd(qualifiedProjection ? preview.commission : null)} note={preview.commission_currency ?? 'IBKR base currency'} /><Metric label="IBKR account daily P&L" value={signedUsd(account.daily_pnl)} tone={tone(account.daily_pnl)} /><Metric label="IBKR account unrealized P&L" value={signedUsd(account.unrealized_pnl)} tone={tone(account.unrealized_pnl)} /><Metric label="Venue reconciliation" value={reconciliation.clean ? 'CLEAN' : 'NOT CLEAN'} note={reconciliation.clean && reconciliation.confirmed_at ? `${reconciliation.method} · ${new Date(reconciliation.confirmed_at).toLocaleString()}` : reconciliation.reason} tone={reconciliation.clean ? 'positive' : 'negative'} /></div>
    <div className="risk-actions"><button onClick={() => onControl('CONFIRM_RECONCILED')}>Confirm venues reconciled</button></div>
  </Panel>
}
